### ISSUE TITLE
raw photos

### ISSUE THREAD

**Issue by ourslfs** [SebaUbuntu/android_packages_apps_Selfie#123]
Option to save raw 16bit images(aka dng format) would be nice. Is this something that could be implemented in the future?

**Comment by luk1337** [comment]
When google adds support for it into CameraX? sure.

**Comment by SebaUbuntu** [comment]
https://groups.google.com/a/android.com/g/camerax-developers/c/qxQGruF80mA/m/HgMk8w8PAgAJ

We're not getting RAW any time soon

**Comment by rmm-fl** [comment]
Looks like CameraX now supports RAW+JPEG simultaneous output since 1.5.0-alpha03:
- https://developer.android.com/jetpack/androidx/releases/camera#1.5.0-alpha03
- https://developer.android.com/reference/androidx/camera/core/ImageCapture#takePicture(androidx.camera.core.ImageCapture.OutputFileOptions,androidx.camera.core.ImageCapture.OutputFileOptions,java.util.concurrent.Executor,androidx.camera.core.ImageCapture.OnImageSavedCallback)

**Comment by luca020400** [comment]
I wish it were that easy, we're using CameraController, and they didn't add support for it there.
It seems easy to do but we can't do it ourselves unless we change androidx code manually

**Comment by luca020400** [comment]
fyi https://review.lineageos.org/c/LineageOS/android_packages_apps_Aperture/+/450957
Since Google doesn't care enough about CameraController I made the changes required to expose the functionality in our camerax fork to let us do all these lovely formats.
